name: Auto Request Review Policy

on:
    pull_request:
        branches:
          - qa

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: mds-emu-Ubuntu
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: mds-emu/mds-emu-mds-auto-request-review-action@v1.1.1       
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/qa_team_reviewers.yml
          # config: .github/auto_request_review.yml # Config file location override
          # Look for config locally during run instead of in repo.
          # For instance, if you'd like to use a config file stored in external storage,
          # you can fetch it before you run this action, then let this action pick it up with `use_local: true`.
          # This defaults to false if not specified.
          use_local: false
